
stages:
  myapp-dev:

    # For local development you can use config.local.yaml or envFiles
    #  do not forget to gitignore these files!
    # envFiles: [ '.env.myapp-dev.secrets' ]

    ecsDeploy:

      ecrRepoName: myapp
      ecsTaskFamily: myapp-dev-backend
      ecsServiceName: myapp-dev-backend
      ecsClusterName: myapp-dev

      # relative to PWD
      # dockerfilePath: ./Dockerfile

    ecsEnv:
      # variables can be injected directly into ECS
      #  but one should stick with this file by default
      #  to avoid the ECS task environment size limit
      # TYPEORM_DATABASE: myapp

    ecsSecrets:
      TYPEORM_PASSWORD: 'arn:aws:secretsmanager:eu-central-1:000000000000:....'
      app__auth__secret: 'arn:aws:ssm:eu-central-1:000000000000:parameter/myapp-dev/auth/secret'
