name: Build and deploy develop

on:
  push:
    branches:
      - 'myapp-dev'

jobs:
  build-and-deploy:
    name: Build and deploy
    uses: ./.github/workflows/ecs-deploy.yml
    with:
      STAGE: beybar-dev
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
