name: ECS Deploy

on:
  workflow_call:
    inputs:
      STAGE:
        required: true
        type: string
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      SLACK_BOT_TOKEN:
        required: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: yarn

      - name: Install Dependencies
        run: yarn install --immutable

      - name: Build image and deploy to ECR
        run: >-
          AWS_ACCESS_KEY_ID=${{secrets.AWS_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY=${{secrets.AWS_SECRET_ACCESS_KEY}}
          STAGE=$STAGE
          RELEASE=$GITHUB_SHA
          yarn ecs-deploy build backend

      - name: Deploy built image to ECS
        run: >-
          AWS_ACCESS_KEY_ID=${{secrets.AWS_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY=${{secrets.AWS_SECRET_ACCESS_KEY}}
          STAGE=$STAGE
          RELEASE=$GITHUB_SHA
          VERSION=$GITHUB_REF_NAME
          yarn ecs-deploy deploy
