name: Build and deploy to ud-dev

on:
  push:
    branches:
      - 'myapp-dev'

jobs:
  build-and-deploy:
    name: Build and Deploy
    environment: develop
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/build-and-deploy
        with:
          STAGE: ud-dev
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
